In [16]:
import numpy as np

In [17]:
#a list of numbers will create a 1D array,
a1D = np.array([1, 2, 3, 4])
a1D


array([1, 2, 3, 4])

In [19]:
#a list of lists will create a 2D array,
a2D = np.array([[1, 2], [3, 4]])

a2D

array([[1, 2],
       [3, 4]])

In [20]:
#numpy.arange creates arrays with regularly incrementing values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [24]:
#numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [26]:

np.linspace(1., 10., 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a.shape
a.dtype.name

'int64'

In [12]:
#refer to the row index:

print(df.loc[0])


calories    420
duration     50
Name: 0, dtype: int64


In [13]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45
